version: 0.2

env:
  parameter-store:
    NPM_TOKEN: /ac/npmjs

phases:
  install:
    runtime-versions:
      nodejs: 18
  build:
    commands:
      - npm run graphql:generate
      - npm run graphql:copydef
      - npm run graphql:transpile
      - npm publish