version: 0.2

env:
  parameter-store:
    NPM_TOKEN: /aspan-corporation/npmjs/automation-token

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install
  build:
    commands:
      - npm run graphql:generate
      - npm run graphql:copydef
      - npm run graphql:transpile
      - npm view @aspan-corporation/common-sigma
      - npm publish