version: 0.2

env:
  parameter-store:
    NPM_TOKEN: /ac/npmjs

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install
  build:
    commands:
      - rm -rf lib
      - npx graphql-codegen --config codegen.yaml
      - cp ./schema.graphql ./lib
      - npx tsc

artifacts:
  files:
    - lib/*
