version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - npm install
  build:
    commands:
      - rm -rf lib
      - npx graphql-codegen --config codegen.yaml
      - cp ./schema.graphql ./lib
      - tsc

artifacts:
  files:
    - packaged-test.yaml
    - packaged-prod.yaml
    - assume-role.sh
    - pipeline/*
